Disable damage in chunks with shooting disable
desertkun/brainout pull request #12
Opened 2022-03-30 21:19 UTC by OcZi

See #9 for more information

Tested and working in freeplay lobby. Main menu lobby is not affected

2022-07-08 19:41 UTC, OcZi commented
Reverting Test command because it would not be used for testing

2023-03-11 20:19 UTC, desertkun requested changes
Could you please rebase your branch and look into comments?

2023-03-11 21:39 UTC, OcZi commented on core/src/com/desertkun/brainout/data/components/HealthComponentData.java
> +        Map map = getMap();
Done. shootingFlag condition will execute now if map is not null

2023-03-11 21:39 UTC, OcZi commented on core/src/com/desertkun/brainout/data/components/HealthComponentData.java
> +            // Log.info("Damage blocked by chunk shooting-disable flag");
Done

2023-03-11 21:43 UTC, OcZi reviewed
Everything should be ok if we only do the check when the map exists

2023-03-12 00:19 UTC, desertkun approved these changes

2023-03-12 00:19 UTC, merged

2023-03-12 00:20 UTC, desertkun commented
@OcZi FYI the project has not an extensive CI that prepares an isolated environment with a build for every pull request. Just select Client build from the CI, download the artifact, and then double-click on the jar